# with extra future, action transition
dataset: ntu
nz: 128
t_his: 10
t_pred: 60
lambda_v: 1000
beta: 0.01
vae_specs:
# rnn model
  model_name: v3_5_4
  rnn_type: gru
  x_birnn: false
  #e_birnn: false
  use_drnn_mlp: true
  is_layernorm: false

# dataset
  n_action: 13
  max_len: 201
  min_len: 35
  t_pre_extra: 50
  is_other_act: true
  data_file: './data/ntu_35_201_wact_candi_{}.npz'

# training
  lambdas: [ 100.0, 100.0, 20.0, 1.0 ]
  act_trans_k: 0.08
  max_trans_fn: 25
  smooth_N: 10
  dct_n: 5
vae_lr: 2.e-3
batch_size: 128
num_vae_epoch: 500
num_vae_epoch_fix: 100
num_vae_data_sample: 4000

